[package]
name = "pwnedkeys-client"
version = "0.1.0"
edition = "2021"

[dependencies]
pwnedkeys-core = { path = "../pwnedkeys-core" }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "http2"] }
thiserror = "1.0"
